import localFont from "next/font/local";
import "../../../styles/main.scss";
import Navbar from "../../components/backoffice/Navbar/Navbar";
import Sidebar from "../../components/backoffice/sidebar/sidebar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "My Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex">
      {/* sidebar */}
      <Sidebar />

      <div className="w-full">
        {/* header */}
        <div className="">
          <Navbar />
        </div>
        {/* main */}
        <main className="p-8 bg-slate-100 dark:bg-[#19192B] text-teal-50 min-h-screen mt-16 ml-60">
          {children}
        </main>
      </div>
      {/* main body */}
    </div>
  );
}
